spring.application.name=gym-backend
spring.config.import=optional:file:.env[.properties]

# Database configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.com.gymguys.gym_backend=TRACE

# cron jobs
# Schedule the task to run every day at midnight
# Daily workout at 12 AM
scheduler.daily.workout=0 0 0 * * *

#scheduler.daily.workout=0 * * * * *

app.jwt.expiration-ms=86400000
app.jwt.secret=${JWT_SECRET}

frontend.url=${FRONTEND_URL}
